rvm:
  - ree
  - 1.8.7
  - 1.9.3
  - 2.0.0

env:
  - "RAILS_VERSION=2.2.0"
  - "RAILS_VERSION=2.3.0"
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"

notifications:
  recipients:
    - kpumuk@kpumuk.info
